# Generated by Django 4.0 on 2021-12-24 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='edit_data',
            field=models.DateField(verbose_name='Дата редактирования'),
        ),
    ]
