# Generated by Django 4.0 on 2021-12-24 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_alter_contact_edit_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='edit_data',
            field=models.DateField(blank=True, null=True, verbose_name='Дата редактирования'),
        ),
    ]
