# Generated by Django 4.0 on 2021-12-24 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_alter_contact_edit_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='info',
            field=models.TextField(default='', verbose_name='Описание'),
            preserve_default=False,
        ),
    ]
