# Generated by Django 4.0 on 2021-12-24 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_contact_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='info',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
    ]
