# Generated by Django 4.0 on 2021-12-28 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_alter_contact_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='edit_data',
            field=models.DateField(auto_now=True, null=True, verbose_name='Дата редактирования'),
        ),
    ]
