# Generated by Django 4.0 on 2021-12-28 17:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0006_alter_contact_edit_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='edit_data',
            field=models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Дата редактирования'),
        ),
    ]
