# Generated by Django 4.0 on 2021-12-29 07:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0007_alter_contact_edit_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='edit_data',
            field=models.DateField(default=datetime.date.today, verbose_name='Дата редактирования'),
        ),
    ]
